{"status":"OK","subtests":[{"name":"no exception is thrown when invoking cancel() twice","status":"PASS"}]}