{"status":"OK","subtests":[{"name":"# AUDIT TASK RUNNER STARTED.","status":"PASS"},{"name":"> [test-suspend] Test suspend() for offline context","status":"PASS"},{"name":"X offlineContext = new OfflineAudioContext(1, 44100, 44100) incorrectly threw ReferenceError: \"Can't find variable: OfflineAudioContext\".","status":"FAIL"},{"name":"Executing \"test-suspend\"","status":"FAIL"},{"name":"< [test-suspend] 1 out of 1 assertions were failed.","status":"FAIL"},{"name":"> [test-resume] Test resume() for offline context","status":"PASS"},{"name":"X p2 = offlineContext.resume() incorrectly threw TypeError: \"undefined is not an object (evaluating 'offlineContext.resume')\".","status":"FAIL"},{"name":"X p2 instanceof Promise is not true. Got false.","status":"FAIL"},{"name":"Executing \"test-resume\"","status":"FAIL"},{"name":"< [test-resume] 2 out of 2 assertions were failed.","status":"FAIL"},{"name":"> [test-after-close] Test state after context closed","status":"PASS"},{"name":"Executing \"test-after-close\"","status":"FAIL"},{"name":"< [test-after-close] All assertions passed. (total 0 assertions)","status":"PASS"},{"name":"> [resume-running-context] Test resuming a running context","status":"PASS"},{"name":"X Create online context incorrectly threw ReferenceError: \"Can't find variable: AudioContext\".","status":"FAIL"},{"name":"Executing \"resume-running-context\"","status":"FAIL"},{"name":"< [resume-running-context] 1 out of 1 assertions were failed.","status":"FAIL"},{"name":"# AUDIT TASK RUNNER FINISHED: 3 out of 4 tasks were failed.","status":"FAIL"}]}